# https://developers.home-assistant.io/docs/add-ons/configuration/#add-on-extended-build
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.14"
  amd64: "ghcr.io/home-assistant/amd64-base:3.14"
  armhf: "ghcr.io/home-assistant/armhf-base:3.14"
  armv7: "ghcr.io/home-assistant/armv7-base:3.14"
  i386: "ghcr.io/home-assistant/i386-base:3.14"
args:
  # renovate: datasource=github-releases depName=deepch/RTSPtoWeb
  RTSPTOWEB_VERSION: v2.4.0
  RTSPTOWEB_REPO: deepch/RTSPtoWeb
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: RTSPtoWebRTC"
  org.opencontainers.image.description: "RTSP Stream to WebBrowser over WebRTC based on Pion."
  org.opencontainers.image.source: "https://github.com/allenporter/stream-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
