# https://developers.home-assistant.io/docs/add-ons/configuration/#add-on-extended-build
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: RTSPtoWebRTC"
  org.opencontainers.image.description: "RTSP Stream to WebBrowser over WebRTC based on Pion."
  org.opencontainers.image.source: "https://github.com/allenporter/stream-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
