# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  # https://github.com/hassio-addons/addon-base
  aarch64: "ghcr.io/hassio-addons/base/amd64:11.0.1"
  amd64: "ghcr.io/hassio-addons/base/amd64:11.0.1"
  armhf: "ghcr.io/hassio-addons/base/armhf:11.0.1"
  armv7: "ghcr.io/hassio-addons/base/armv7:11.0.1"
  i386: "ghcr.io/hassio-addons/base/i386:11.0.1"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: RTSPtoWebRTC"
  org.opencontainers.image.description: "RTSP Stream to WebBrowser over WebRTC based on Pion."
  org.opencontainers.image.source: "https://github.com/allenporter/stream-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
