# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: RTSPtoWeb - WebRTC
version: "1.0.1"
slug: rtsp-to-web
description: RTSP Stream to WebBrowser over WebRTC and other protocols based on Pion
url: "https://github.com/allenporter/stream-addons/tree/main/rtsp-to-web"
panel_icon: mdi:webrtc
webui: "http://[HOST]:[PORT:8083]"
host_network: true
discovery: ["rtsp_to_webrtc"]
watchdog: "http://[HOST]:[PORT:8083]/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  debug: false
  http_port: 8083
  rtsp_port: 5541
  log_level: info
schema:
  debug: bool
  http_port: int
  rtsp_port: int
  log_level: list(trace|debug|info|warn|error|fatal|panic)
init: false
#image: "ghcr.io/allenporter/{arch}-rtsp-to-web"
