# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: RTSPtoWebRTC
version: "1.0.1"
slug: rtsp-to-webrtc
description: RTSP Stream to WebBrowser over WebRTC based on Pion
url: "https://github.com/allenporter/stream-addons/tree/main/rtsp-to-webrtc"
panel_icon: mdi:webrtc
ports:
  8083/tcp: 8083
ports_description:
  8083/tcp: "RTSPtoWebRTC server"
host_network: true
discovery: ["rtsp_to_webrtc"]
watchdog: "http://[HOST]:[PORT:8083]/static"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
image: "ghcr.io/allenporter/{arch}-rtsp-to-webrtc"
